### ISSUE TITLE
About QA section in run.sh

### ISSUE THREAD

**Issue by Rcrossmeister** [Rcrossmeister/RLQG#2]
Hello, may I ask if run.sh has not updated the OpenAI QA section yet

**Comment by Rcrossmeister** [comment]
Hi @donggedashao,

Regarding your question in #1: _"Hello, may I ask if run.sh has not updated the OpenAI QA section yet?"_

If you're asking why the evaluation part (e.g., using the OpenAI API as a QA model) isn't included in `run.sh`, it's because `run.sh` is designed to train the QG model and generate the final questions. The QA evaluation should be conducted after `run.sh` is completed.

If you're referring to the QA module used during the training part in `run.sh`, we generate over 10,000 intermediate questions using the SFT model and answer them by Llama-2 QA model to get the QA reward. Using the OpenAI API for this would be very costly. However, if you'd like to replace the QA module, you can use the following code:
```
python ../evaluation/openai_qa.py \
    --api_key [your-api-key] \
    --api_model [your-api-model] \
    --input_path [path-to-QG-file] \
    --num_shots 5 
```
This script will work well, but please be mindful of the API costs.

I hope this answers your question. Thanks.

**Comment by donggedashao** [comment]
Thank you very much for your patient answer!

**Comment by Rcrossmeister** [comment]
Feel free to re-open if needed.
