### ISSUE TITLE
Request for Help about /dataset_info.json.

### ISSUE THREAD

**Issue by lx-bistu** [Rcrossmeister/RLQG#4]
Please update the relevant details of the dataset_info.json.

Thank you!!!

**Comment by Rcrossmeister** [comment]
Thanks for you reminder, I will finish the upload soon.

**Comment by Rcrossmeister** [comment]
I have updated the corresponding file at `./model/data/dataset_info.json`, please check.

Thanks for your patience and sorry for the delay.
